name: github actions build exe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup
        run: echo "running in bash"
        shell: bash
        
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          python -m pip install pyinstaller
        shell: bash
          
      - name: Build .exe
        run: |
          python -m PyInstaller --onefile --noconfirm --windowed main.py
          
      - name: Check that .exe exists
        run: |
          if [[ -f ./dist/main.exe ]]; then
            echo ".exe file created successfully"
          else
            exit 1
          fi
        shell: bash     
        
